sudo: false
language: cpp
python:
  - "3.6"
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
            - sourceline: 'ppa:cs50/ppa'
          packages:
            - astyle
      env:
        - DESC="Check code style"
        - TEST="true"

    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - DESC="AppImage deploy"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - QTV="qt510"

    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - DESC="AppImage deploy for QGC"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - QTV="qt59"

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env:
        - DESC="dmg deploy"
        - MATRIX_EVAL="COMPILER=clang++"

install:
- if [ -z $TEST ]; then
    pip install --user --upgrade pip;
    pip install --user jinja2;
  fi
- if [[ "${TRAVIS_OS_NAME}" = "linux" && -z $TEST ]]; then
    if [ "${QTV}" = "qt59" ]; then
      sudo add-apt-repository --yes ppa:beineri/opt-qt594-trusty;
    else
      sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty;
    fi;
    sudo apt update -qq;
    sudo apt search ${QTV};
    sudo apt install build-essential ${QTV}-meta-minimal ${QTV}charts-no-lgpl
    ${QTV}quickcontrols ${QTV}quickcontrols2 ${QTV}serialport
    ${QTV}graphicaleffects ${QTV}svg ${QTV}scxml git;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update > /dev/null;
    brew install qt5;
    chmod -R 755 /usr/local/opt/qt5/*;
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
  fi

script:
- if [ ! -z $TEST ]; then
    ./tools/astyle.sh;
    git diff;
    if ! git diff --quiet --ignore-submodules HEAD 2>/dev/null; then
      echo "Style error ! Run astyle in tools. (./tools/astyle.sh)";
      exit 1;
    fi;
  fi
- if [[ "${TRAVIS_OS_NAME}" = "linux" && -z $TEST ]]; then
    source /opt/qt*/bin/qt*-env.sh;
    git submodule init;
    git submodule update;
    mkdir build;
    cd build;
    qmake ..;
    make;
    mkdir deploy;
    ls ../qml/;
    ls ../qml/imgs;
    cp ../qml/imgs/pingviewer.png deploy/;
    cp ../deploy/pingviewer.desktop deploy/;
    mv pingviewer deploy/;
    wget https://github.com/bluerobotics/stm32flash-code/releases/download/continuous/stm32flash_linux.zip;
    unzip stm32flash_linux.zip;
    chmod +x stm32flash;
    mv stm32flash deploy/;
    ls deploy;
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
    ./linuxdeployqt*.AppImage deploy/pingviewer -verbose=2 -qmldir=../qml -bundle-non-qt-libs -extra-plugins=imageformats/libqsvg.so,iconengines/libqsvgicon.so;
    ./linuxdeployqt*.AppImage deploy/pingviewer.desktop -verbose=2 -qmldir=../qml -appimage;
    find . | grep AppImage;
    if [ "${QTV}" = "qt59" ]; then
      mv pingviewer-x86_64.AppImage ./pingviewer-x86_64_QGC.AppImage;
    fi;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    git submodule init;
    git submodule update;
    mkdir build;
    cd build;
    qmake ..;
    make;
    find .;
    wget https://github.com/bluerobotics/stm32flash-code/releases/download/continuous/stm32flash_osx.zip;
    unzip stm32flash_osx.zip;
    chmod +x stm32flash;
    mv stm32flash pingviewer.app/;
    macdeployqt pingviewer.app/ -qmldir=../qml -dmg;
  fi

after_success:
- if [ -z $TEST ]; then
    wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh;
  fi
- if [[ "${TRAVIS_OS_NAME}" = "linux" && -z $TEST ]]; then
    bash ./upload.sh ./pingviewer*.AppImage;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then bash ./upload.sh pingviewer*.dmg*; fi